package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os/signal"
	"runtime/debug"
	"syscall"
	"time"

	"github.com/levskiy0/webpprof"
	"github.com/levskiy0/webpprof/example/customprofiler"
	webpprofhttp "github.com/levskiy0/webpprof/profiler/http"
)

const address = "127.0.0.1:3030"

func main() {
	mux := http.NewServeMux()
	profiler := webpprof.New(
		mux,
		webpprof.WithRetention(time.Hour),
		webpprof.WithExcludedRequests("GET /favicon.ico"),
	)
	defer profiler.Close()

	// A custom profiler wraps an existing dependency once in the composition
	// root. Application code continues to depend only on the original interface.
	client := customprofiler.ProfileWith(profiler, demoClient{})
	app := &demoApp{profiler: profiler, client: client}
	appMux := http.NewServeMux()
	appMux.HandleFunc("GET /", app.home)
	appMux.HandleFunc("GET /demo", app.demo)
	appMux.HandleFunc("GET /panic", app.panic)

	// The profiler routes are already registered on mux. The fallback route
	// wraps only the demo application and supplies request correlation context.
	// Named wrappers become Middleware entries under the captured request.
	profiledApp := webpprofhttp.ProfileMiddlewareWith(profiler, "security-headers", securityHeaders)(
		webpprofhttp.ProfileMiddlewareWith(profiler, "request-log", requestLog)(appMux),
	)
	// Tagging runs after request capture and before named middleware. WithTags
	// updates the request capture and is inherited by every child entity.
	taggedApp := demoTags(profiledApp)
	mux.Handle("/", recoverResponse(webpprofhttp.MiddlewareWith(profiler, taggedApp)))

	server := &http.Server{
		Addr:              address,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	serverErrors := make(chan error, 1)
	go func() {
		log.Printf("demo:     http://%s/", address)
		log.Printf("webpprof: http://%s%s/", address, profiler.BasePath())
		serverErrors <- server.ListenAndServe()
	}()

	select {
	case <-ctx.Done():
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := server.Shutdown(shutdownCtx); err != nil {
			log.Printf("shutdown: %v", err)
		}
	case err := <-serverErrors:
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("server: %v", err)
		}
	}
}

type demoApp struct {
	profiler *webpprof.Profiler
	client   customprofiler.Client
}

func (a *demoApp) home(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(homePage))
}

func (a *demoApp) demo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	failed := r.URL.Query().Has("fail")
	startedAt := time.Now().UTC()
	rows := int64(1)
	lookupKey := "player:42"
	if failed {
		lookupKey = "player:missing"
	}

	// This is a normal dependency call. The wrapper in customprofiler measures
	// it and records a request-related custom Event without changing this handler.
	_, _ = a.client.Lookup(ctx, lookupKey)

	// Each Log*Context call becomes a Related tab under this HTTP request.
	a.profiler.LogQueryContext(ctx, webpprof.Query{
		Meta: webpprof.Meta{
			StartedAt: startedAt,
			Duration:  12 * time.Millisecond,
			// This entity-specific tag is merged with app, tenant, and scenario
			// tags inherited from the request context.
			Tags: map[string]string{"repository": "players"},
		},
		Connection:   "example",
		Driver:       "sqlite",
		Database:     "local",
		Operation:    "SELECT",
		SQL:          "SELECT id, email FROM players WHERE id = 42",
		RowsAffected: &rows,
	})
	a.profiler.LogCacheContext(ctx, webpprof.Cache{
		Meta:      webpprof.Meta{StartedAt: startedAt.Add(13 * time.Millisecond), Duration: 800 * time.Microsecond},
		Store:     "memory",
		Operation: "get",
		Key:       "player:42",
		Hit:       true,
		TTL:       time.Minute,
		Value:     `{"id":42,"name":"Ada"}`,
	})
	a.profiler.LogEmailContext(ctx, webpprof.Email{
		Meta:      webpprof.Meta{StartedAt: startedAt.Add(15 * time.Millisecond), Duration: 8 * time.Millisecond},
		Transport: "smtp",
		From:      webpprof.Address{Name: "Example", Email: "hello@example.test"},
		To:        []webpprof.Address{{Name: "Ada", Email: "ada@example.test"}},
		Subject:   "Welcome to webpprof",
		Text:      "This message was generated by the local example.",
		Status:    "sent",
	})
	a.profiler.LogJobContext(ctx, webpprof.Job{
		Meta:       webpprof.Meta{StartedAt: startedAt.Add(24 * time.Millisecond), Duration: 2 * time.Millisecond},
		Name:       "SendWelcomeEmail",
		Queue:      "mail",
		Connection: "sync",
		State:      "dispatched",
		Arguments:  []webpprof.Argument{{Name: "player_id", Type: "uint64", Value: "42"}},
	})
	a.profiler.LogLogContext(ctx, webpprof.Log{
		Meta:    webpprof.Meta{StartedAt: startedAt.Add(27 * time.Millisecond)},
		Level:   "INFO",
		Message: "example request handled",
		Fields:  map[string]any{"player_id": 42, "failed": failed},
	})
	a.profiler.LogHTTPCallContext(ctx, webpprof.HTTPCall{
		Meta:         webpprof.Meta{StartedAt: startedAt.Add(28 * time.Millisecond), Duration: 15 * time.Millisecond},
		Method:       http.MethodGet,
		URL:          "https://api.example.test/avatars/42",
		Status:       http.StatusOK,
		ResponseSize: 2048,
	})
	a.profiler.LogScheduleContext(ctx, webpprof.Schedule{
		Meta:      webpprof.Meta{StartedAt: startedAt.Add(44 * time.Millisecond), Duration: time.Millisecond},
		Name:      "refresh-player",
		State:     "succeeded",
		PlannedAt: startedAt,
		Payload: map[string]any{
			"player_id": 42,
			"tenant":    webpprof.TagsFromContext(ctx)["tenant"],
			"force":     failed,
			"resources": []string{"profile", "avatar", "permissions"},
		},
	})
	a.profiler.LogEventContext(ctx, webpprof.Event{
		Meta:    webpprof.Meta{StartedAt: startedAt.Add(46 * time.Millisecond)},
		Kind:    "player",
		Name:    "viewed",
		Status:  "recorded",
		Summary: "Player 42 was opened in the local example",
		Fields:  map[string]any{"player_id": 42},
	})

	status := http.StatusOK
	if failed {
		status = http.StatusInternalServerError
		err := errors.New("synthetic example failure")
		a.profiler.LogExceptionContext(ctx, webpprof.Exception{
			Meta:    webpprof.Meta{StartedAt: startedAt.Add(47 * time.Millisecond)},
			Type:    fmt.Sprintf("%T", err),
			Message: err.Error(),
			Stack:   string(debug.Stack()),
		})
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]any{
		"ok":       !failed,
		"message":  "Open webpprof and inspect the newest request",
		"profiler": profilerURL(r, a.profiler),
	})
}

func (a *demoApp) panic(http.ResponseWriter, *http.Request) {
	panic("synthetic example panic")
}

type demoClient struct{}

func (demoClient) Lookup(_ context.Context, key string) (string, error) {
	if key == "player:missing" {
		return "", errors.New("example client: player not found")
	}
	return "Ada", nil
}

func profilerURL(r *http.Request, profiler *webpprof.Profiler) string {
	return "http://" + r.Host + profiler.BasePath() + "/"
}

func recoverResponse(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if recovered := recover(); recovered != nil {
				http.Error(w, fmt.Sprint(recovered), http.StatusInternalServerError)
			}
		}()
		next.ServeHTTP(w, r)
	})
}

func demoTags(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		tenant := r.URL.Query().Get("tenant")
		if tenant == "" {
			tenant = "acme"
		}
		scenario := "success"
		if r.URL.Query().Has("fail") || r.URL.Path == "/panic" {
			scenario = "failure"
		}
		ctx := webpprof.WithTags(r.Context(), map[string]string{
			"app":      "example",
			"tenant":   tenant,
			"scenario": scenario,
		})
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

func securityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Content-Type-Options", "nosniff")
		next.ServeHTTP(w, r)
	})
}

func requestLog(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Printf("%s %s", r.Method, r.URL.RequestURI())
		next.ServeHTTP(w, r)
	})
}

const homePage = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>webpprof local example</title>
  <style>
    body { max-width: 760px; margin: 64px auto; padding: 0 24px; color: #252936; background: #f5f6f8; font: 16px/1.6 system-ui, sans-serif; }
    main { padding: 32px; border: 1px solid #dde0e6; border-radius: 12px; background: white; box-shadow: 0 14px 40px #1f29370f; }
    h1 { margin: 0 0 8px; line-height: 1.2; }
    p { color: #68707d; }
    nav { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 24px; }
    a { padding: 9px 14px; border: 1px solid #d7d9e1; border-radius: 7px; color: #5154c9; text-decoration: none; }
    a:hover { border-color: #777ae0; background: #f0f1ff; }
    a.primary { border-color: #5558cf; color: white; background: #5558cf; }
    code { padding: 2px 5px; border-radius: 4px; background: #eff0f3; }
  </style>
</head>
<body>
  <main>
    <h1>webpprof local example</h1>
    <p>Generate a request, then open the profiler and inspect its Related tabs. Every demo request also passes through the custom profiler in <code>example/customprofiler</code>.</p>
    <nav>
      <a class="primary" href="/demo?tenant=acme">Acme success</a>
      <a href="/demo?tenant=umbrella">Umbrella success</a>
      <a href="/demo?tenant=acme&amp;fail=1">Acme failure</a>
      <a href="/panic?tenant=umbrella">Umbrella panic</a>
      <a href="/debug/webpprof/">Open webpprof</a>
    </nav>
    <p>Stop the server with <code>Ctrl+C</code>.</p>
  </main>
</body>
</html>`
